import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#f8fafc" },
    header: {
        backgroundColor: "#5596e0",
        paddingHorizontal: 20,
        paddingTop: 54,
        paddingBottom: 40,
        borderBottomLeftRadius: 28,
        borderBottomRightRadius: 28,
        elevation: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
    },
    headerTopBar: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    profileSection: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
        marginRight: 10,
    },
    avatarContainer: {
        width: 42,
        height: 42,
        borderRadius: 21,
        backgroundColor: "rgba(255,255,255,0.15)",
        justifyContent: "center",
        alignItems: "center",
        position: "relative",
    },
    avatarImage: {
        width: 42,
        height: 42,
        borderRadius: 21,
    },
    avatarText: {
        color: "#ffffff",
        fontSize: 16,
        fontWeight: "bold",
    },
    avatarStatus: {
        position: "absolute",
        bottom: 0,
        right: 0,
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: "#10b981",
        borderWidth: 1.5,
        borderColor: "#5596e0",
    },
    profileTextWrapper: { marginLeft: 10, flex: 1 },
    greetingLabel: { color: "#cccccc", fontSize: 12 },
    profileName: { color: "#ffffff", fontSize: 15, fontWeight: "bold" },
    eyeBtn: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: "rgba(255,255,255,0.1)",
        justifyContent: "center",
        alignItems: "center",
    },
    bankCard: {
        backgroundColor: "#1e293b",
        borderRadius: 18,
        padding: 20,
        borderWidth: 1,
        borderColor: "rgba(255,255,255,0.1)",
        elevation: 6,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
    },
    cardHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 14,
    },
    cardBrandWrapper: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    cardBrandText: {
        color: "#f59e0b",
        fontSize: 11,
        fontWeight: "bold",
        letterSpacing: 1,
    },
    cardChip: {
        width: 32,
        height: 24,
        borderRadius: 4,
        backgroundColor: "#f59e0b",
        opacity: 0.8,
        marginLeft: 10
    },
    cardBalanceLabel: {
        color: "#94a3b8",
        fontSize: 10,
        letterSpacing: 0.5,
    },
    cardBalanceLabelContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 4,
    },
    cardBalanceAmount: {
        color: "#ffffff",
        fontSize: 28,
        fontWeight: "bold",
    },
    cardStats: {
        flexDirection: "row",
        backgroundColor: "rgba(255,255,255,0.07)",
        borderRadius: 12,
        padding: 12,
        alignItems: "center",
    },
    cardStat: { flex: 1 },
    cardStatDivider: {
        width: 1,
        height: 30,
        backgroundColor: "rgba(255,255,255,0.2)",
        marginHorizontal: 12,
    },
    cardStatLabelContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 4,
    },
    cardStatLabel: {
        color: "#94a3b8",
        fontSize: 10,
        letterSpacing: 0.5,
    },
    cardStatValue: { color: "#ffffff", fontSize: 14, fontWeight: "bold" },
    helpIconTouch: {
        padding: 2,
        marginLeft: 4,
        justifyContent: "center",
        alignItems: "center",
    },
    // Legacy styles kept for references but no longer used in header
    headerRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 20 },
    headerTitle: { fontSize: 16, color: "#fdf4ff", opacity: 0.9 },
    headerSubtitle: { fontSize: 13, color: "#fdf4ff", opacity: 0.7, marginTop: 4 },
    unallocatedBox: { flexDirection: "row", alignItems: "center", marginBottom: 20 },
    unallocatedAmount: { color: "#ffffff", fontSize: 32, fontWeight: "bold", marginLeft: 10 },
    headerCards: { flexDirection: "row", backgroundColor: "rgba(255,255,255,0.15)", borderRadius: 20, padding: 16, alignItems: "center" },
    headerCard: { flex: 1 },
    headerDivider: { width: 1, height: 35, backgroundColor: "rgba(255,255,255,0.3)", marginHorizontal: 12 },
    headerCardLabel: { color: "#ede9fe", fontSize: 13, marginBottom: 4 },
    headerCardValue: { color: "#ffffff", fontSize: 17, fontWeight: "bold" },
    body: { flex: 1 },
    bodyContent: { paddingHorizontal: 20, paddingTop: 10 },
    tabSection: {
        paddingHorizontal: 20,
        marginTop: -25,
        zIndex: 10,
    },
    tabContainer: {
        flexDirection: "row",
        backgroundColor: "#ffffff",
        borderRadius: 16,
        padding: 6,
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
    },
    tab: {
        flex: 1,
        paddingVertical: 12,
        alignItems: "center",
        borderRadius: 12,
    },
    tabActive: {
        backgroundColor: "#7c3aed",
    },
    tabText: {
        fontSize: 15,
        fontWeight: "600",
        color: "#64748b",
    },
    tabTextActive: {
        color: "#ffffff",
    },
    sectionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginTop: 24,
        marginBottom: 16,
    },
    sectionTitle: { fontSize: 18, fontWeight: "bold", color: "#1e293b" },
    addCatBtn: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#f5f3ff",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
        gap: 4,
    },
    addCatText: { color: "#7c3aed", fontWeight: "bold", fontSize: 13 },
    emptyBox: {
        backgroundColor: "#ffffff",
        borderRadius: 20,
        padding: 40,
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#f1f5f9",
        marginTop: 20,
        elevation: 1,
    },
    emptyText: {
        color: "#94a3b8",
        textAlign: "center",
        lineHeight: 22,
        fontSize: 15,
    },
    catCard: {
        backgroundColor: "#ffffff",
        borderRadius: 20,
        marginBottom: 14,
        flexDirection: "row",
        alignItems: "center",
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
    },
    catInfo: { flex: 1 },
    catNameRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    catName: { fontSize: 17, fontWeight: "bold", color: "#334155" },
    catBudget: { fontSize: 16, fontWeight: "bold" },
    progressContainer: { marginTop: 16 },
    progressTrack: {
        height: 8,
        backgroundColor: "#f1f5f9",
        borderRadius: 4,
        overflow: "hidden",
    },
    progressFill: { height: "100%", borderRadius: 4 },
    progressLabelRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginTop: 6,
    },
    progressText: { fontSize: 13, color: "#64748b" },
    progressPercent: { fontSize: 13, fontWeight: "600", color: "#64748b" },
    deleteBtn: { padding: 10, marginLeft: 10 },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(15, 23, 42, 0.7)",
        justifyContent: "flex-start",
    },
    modalContent: {
        backgroundColor: "#ffffff",
        borderRadius: 24,
        padding: 24,
        paddingBottom: 40,
        paddingTop: 90,
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    modalTitle: { fontSize: 19, fontWeight: "bold", color: "#0f172a" },
    allocTabs: {
        flexDirection: "row",
        backgroundColor: "#f1f5f9",
        borderRadius: 12,
        padding: 4,
        marginBottom: 20,
    },
    allocTab: {
        flex: 1,
        paddingVertical: 10,
        alignItems: "center",
        borderRadius: 10,
    },
    allocTabActiveDeposit: { backgroundColor: "#10b981" },
    allocTabActiveWithdraw: { backgroundColor: "#ef4444" },
    allocTabText: { fontWeight: "bold", color: "#64748b" },
    allocTabTextActive: { color: "#ffffff" },
    modalSubtitle: { fontSize: 15, color: "#64748b", marginBottom: 16 },
    modalHighlight: { color: "#0f172a", fontWeight: "bold" },
    amountDisplayModal: {
        backgroundColor: "#f8fafc",
        borderRadius: 16,
        padding: 20,
        alignItems: "center",
        flexDirection: "row",
        justifyContent: "center",
        marginBottom: 20,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    amountTextModal: { fontSize: 32, fontWeight: "bold", color: "#0f172a" },
    currencyLabelModal: {
        fontSize: 16,
        color: "#64748b",
        marginLeft: 8,
        marginTop: 8,
    },
    actionButtonRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        gap: 12,
        marginTop: 24,
    },
    actionConfirmBtn: {
        flex: 1,
        height: 54,
        borderRadius: 16,
        alignItems: "center",
        justifyContent: "center",
    },
    actionCancelBtn: {
        alignSelf: 'flex-end',

    },
    confirmDisabled: {
        backgroundColor: "#cbd5e1",
        elevation: 0,
        shadowOpacity: 0,
    },
    cancelBtnText: {
        color: "#ef4444",
        fontSize: 16,
        fontWeight: "bold",
    },
    confirmBtnText: {
        color: "#ffffff",
        fontSize: 16,
        fontWeight: "bold",
    },
    confirmBtn: {
        backgroundColor: "#7c3aed",
        paddingVertical: 16,
        borderRadius: 16,
        alignItems: "center",
        marginTop: 24,
    },
    modalOverlayCenter: {
        flex: 1,
        backgroundColor: "rgba(15, 23, 42, 0.6)",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
    },
    inputModalContent: {
        backgroundColor: "#ffffff",
        borderRadius: 24,
        padding: 24,
        width: "100%",
        elevation: 20,
    },
    textInput: {
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
        fontSize: 16,
        color: "#0f172a",
        marginBottom: 16,
        backgroundColor: "#f8fafc",
        textAlignVertical: "center",
    },
    typeLabel: {
        fontSize: 14,
        fontWeight: "600",
        color: "#64748b",
        marginBottom: 10,
    },
    typeToggleRow: { flexDirection: "row", gap: 10, marginBottom: 20 },
    typeToggleBtn: {
        flex: 1,
        paddingVertical: 12,
        alignItems: "center",
        borderRadius: 10,
        backgroundColor: "#f1f5f9",
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    typeToggleBtnActive: { backgroundColor: "#7c3aed", borderColor: "#7c3aed" },
    typeToggleText: { fontSize: 14, color: "#64748b", fontWeight: "600" },
    typeToggleTextActive: { color: "#ffffff" },
    listSection: { marginBottom: 10 },
    listSectionTitle: {
        fontSize: 14,
        fontWeight: "bold",
        color: "#64748b",
        marginBottom: 12,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    deleteMsg: {
        fontSize: 14,
        color: "#475569",
        lineHeight: 22,
        marginBottom: 12,
    },
    warningBox: {
        backgroundColor: "#fff7ed",
        padding: 12,
        borderRadius: 12,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: "#fed7aa",
    },
    warningText: { fontSize: 13, color: "#c2410c", lineHeight: 18 },
    deleteLabel: {
        fontSize: 14,
        fontWeight: "600",
        color: "#334155",
        marginTop: 10,
        marginBottom: 4,
    },
    requiredText: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#ef4444",
        marginBottom: 12,
        backgroundColor: "#fef2f2",
        padding: 10,
        borderRadius: 8,
        textAlign: "center",
        borderStyle: "dashed",
        borderWidth: 1,
        borderColor: "#fca5a5",
    },
    tabNoteBox: {
        backgroundColor: "#eff6ff",
        paddingVertical: 4,
        paddingHorizontal: 12,
        borderRadius: 12,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: "#bfdbfe",
    },
    tabNoteText: {
        fontSize: 10,
        color: "#1e40af",
        lineHeight: 18,
        fontWeight: "500",
    },
    inputMethodToggleRow: {
        flexDirection: "row",
        paddingHorizontal: 6,
        marginBottom: 16,
        marginTop: 10,
    },
    quickToggleBtnCircle: {
        backgroundColor: "#ffffff",
        width: 34,
        height: 34,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    manualInputWrapper: {
        marginBottom: 20,
    },
    manualInput: {
        backgroundColor: "#f8fafc",
        borderWidth: 2,
        borderColor: "#e2e8f0",
        borderRadius: 16,
        padding: 20,
        fontSize: 24,
        fontWeight: "bold",
        color: "#0f172a",
        textAlign: "center",
    },
    catIconContainer: {
        width: 44,
        height: 44,
        borderRadius: 12,
        backgroundColor: "#f5f3ff",
        justifyContent: "center",
        alignItems: "center",
        marginRight: 14,
    },
    catIcon: {
        width: 32,
        height: 32,
        resizeMode: "contain",
    },
    iconModalContent: {
        backgroundColor: "#ffffff",
        borderRadius: 24,
        padding: 24,
        width: "100%",
        maxHeight: "80%",
        elevation: 20,
    },
    iconModalSubtitle: {
        fontSize: 14,
        color: "#64748b",
        marginBottom: 16,
        lineHeight: 20,
    },
    iconGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        gap: 12,
        paddingVertical: 10,
    },
    iconGridItem: {
        width: "22%",
        aspectRatio: 1,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        backgroundColor: "#f8fafc",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 4,
    },
    iconItemImage: {
        width: 38,
        height: 38,
        resizeMode: "contain",
    },
    // ultils
    rowmb10: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 10,
    },
    row: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    }
});