import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
    },
    header: {
        backgroundColor: "#3b82f6",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingVertical: 16,
        paddingTop: Platform.OS === "android" ? 40 : 16,
    },
    backButton: {
        padding: 8,
        marginLeft: -8,
    },
    headerTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#ffffff",
    },
    scrollContent: {
        padding: 16,
    },
    introBox: {
        backgroundColor: "#ffffff",
        padding: 16,
        borderRadius: 12,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    introText: {
        fontSize: 15,
        color: "#334155",
        lineHeight: 22,
    },
    section: {
        marginBottom: 32,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#0f172a",
        marginBottom: 8,
    },
    guideText: {
        fontSize: 15,
        color: "#475569",
        lineHeight: 22,
        marginBottom: 16,
    },
    mockupContainer: {
        backgroundColor: "#f1f5f9",
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    mockCard: {
        backgroundColor: "#ffffff",
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: "#bfdbfe",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    mockRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 16,
    },
    iconCircle: {
        width: 48,
        height: 48,
        borderRadius: 24,
        alignItems: "center",
        justifyContent: "center",
    },
    mockLabel: {
        fontSize: 14,
        color: "#64748b",
        fontWeight: "500",
    },
    mockLabelRed: {
        fontSize: 16,
        color: "#ef4444",
        fontWeight: "bold",
    },
    mockValueBlue: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#3b82f6",
        marginTop: 2,
    },
    mockBtnBlue: {
        backgroundColor: "#3b82f6",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        borderRadius: 8,
    },
    mockBtnText: {
        color: "#ffffff",
        fontWeight: "bold",
        fontSize: 15,
    },
    mockFlow: {
        alignItems: "center",
    },
    mockPillBlue: {
        backgroundColor: "#3b82f6",
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 20,
    },
    mockPillText: {
        color: "#fff",
        fontWeight: "bold",
    },
    mockGrid: {
        flexDirection: "row",
        gap: 12,
        width: "100%",
    },
    mockCategory: {
        flex: 1,
        backgroundColor: "#ffffff",
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        alignItems: "center",
    },
    mockCatName: {
        fontSize: 14,
        fontWeight: "600",
        color: "#334155",
    },
    mockCatValue: {
        fontSize: 15,
        fontWeight: "bold",
        color: "#10b981",
        marginTop: 4,
        marginBottom: 8,
    },
    mockActionBadge: {
        backgroundColor: "#f1f5f9",
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 12,
    },
    mockActionBadgeText: {
        fontSize: 12,
        color: "#64748b",
        fontWeight: "bold",
        textAlign: "center",
    },
    mockGuideSubText: {
        fontSize: 14,
        color: "#334155",
        marginBottom: 8,
    },
    mockPiggyCard: {
        backgroundColor: "#ffffff",
        borderRadius: 12,
        padding: 16,
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#fbcfe8",
    },
    noteItem: {
        flexDirection: "row",
        marginBottom: 12,
        alignItems: "flex-start",
        backgroundColor: "#fffbeb",
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#fde68a",
    },
    noteText: {
        fontSize: 14,
        color: "#451a03",
        lineHeight: 20,
        marginLeft: 8,
        flex: 1,
    },
    footerSpace: {
        height: 40,
    },
    mockSectionLabel: {
        fontSize: 13,
        fontWeight: "700",
        color: "#64748b",
        marginBottom: 10,
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    mockTotalBar: {
        backgroundColor: "#1e293b",
        borderRadius: 10,
        paddingVertical: 10,
        paddingHorizontal: 16,
        alignItems: "center",
        marginBottom: 4,
    },
    mockTotalAmount: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#ffffff",
    },
    mockGroupLabel: {
        fontSize: 12,
        fontWeight: "600",
        color: "#94a3b8",
        marginBottom: 8,
        textTransform: "uppercase",
    },
    mockFundRow: {
        flexDirection: "row",
        gap: 10,
    },
    mockFundCard: {
        flex: 1,
        backgroundColor: "#ffffff",
        borderRadius: 12,
        padding: 12,
        alignItems: "center",
        borderWidth: 1.5,
    },
    mockFundIcon: {
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 6,
    },
    mockFundName: {
        fontSize: 12,
        fontWeight: "600",
        color: "#334155",
        marginBottom: 4,
        textAlign: "center",
    },
    mockFundBalance: {
        fontSize: 13,
        fontWeight: "bold",
        textAlign: "center",
    },
    mockTransferBox: {
        backgroundColor: "#ffffff",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        overflow: "hidden",
    },
    mockTransferRow: {
        flexDirection: "row",
    },
    mockTransferBtn: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 6,
        paddingVertical: 14,
    },
    mockTransferDivider: {
        width: 1,
        backgroundColor: "#e2e8f0",
    },
    mockTransferText: {
        fontSize: 14,
        fontWeight: "bold",
    },
    mockTransferNote: {
        fontSize: 12,
        color: "#64748b",
        textAlign: "center",
        paddingVertical: 10,
        borderTopWidth: 1,
        borderColor: "#f1f5f9",
        lineHeight: 18,
    },
    mockChartBox: {
        backgroundColor: "#ffffff",
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    mockChartHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        marginBottom: 16,
    },
    mockChartTitle: {
        fontSize: 15,
        fontWeight: "bold",
        color: "#0f172a",
    },
    mockPieContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-around",
        marginBottom: 20,
    },
    mockPieCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: "#f1f5f9",
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 2,
        borderColor: "#e2e8f0",
    },
    mockLegend: {
        gap: 4,
    },
    mockLegendItem: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    legendDot: {
        width: 8,
        height: 8,
        borderRadius: 4,
    },
    legendText: {
        fontSize: 12,
        color: "#475569",
    },
    mockBarContainer: {
        borderTopWidth: 1,
        borderTopColor: "#f1f5f9",
        paddingTop: 12,
    },
    mockBarHeader: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        marginBottom: 10,
    },
    mockChartTitleSmall: {
        fontSize: 13,
        fontWeight: "bold",
        color: "#334155",
    },
    mockBarRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        marginBottom: 8,
    },
    mockBarTrack: {
        flex: 1,
        height: 8,
        backgroundColor: "#f1f5f9",
        borderRadius: 4,
        overflow: "hidden",
    },
    mockBarFill: {
        height: "100%",
        borderRadius: 4,
    },
    mockBarLabel: {
        width: 30,
        fontSize: 12,
        fontWeight: "600",
        color: "#64748b",
    },
    goldNavButton: {
        backgroundColor: "#d97706",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        borderRadius: 8,
        shadowColor: "#d97706",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 2,
    },
    goldNavButtonText: {
        color: "#ffffff",
        fontWeight: "bold",
        fontSize: 15,
    },
});