import { StyleSheet } from "react-native";

export const NAVY = "#0c2340";

// ─── STYLES ───────────────────────────────────────────────────────────────────
export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#f1f5f9" },

    // Header
    header: {
        backgroundColor: NAVY,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 12,
        paddingVertical: 14,
    },
    headerBtn: { padding: 6, minWidth: 36, alignItems: "center" },
    headerTitle: {
        fontSize: 17,
        fontWeight: "700",
        color: "#fff",
        flex: 1,
        textAlign: "center",
    },
    headerSaveBtn: {
        backgroundColor: "rgba(255,255,255,0.18)",
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 20,
    },
    headerSaveTxt: { color: "#fff", fontWeight: "700", fontSize: 14 },

    scroll: { paddingBottom: 16 },

    // ── Hero Card ──
    heroCard: {
        backgroundColor: "#fff",
        marginHorizontal: 0,
        alignItems: "center",
        paddingBottom: 24,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
    },
    heroBanner: {
        width: "100%",
        height: 90,
        backgroundColor: NAVY,
    },
    avatarRing: {
        width: 160,
        height: 160,
        borderRadius: 80,
        borderWidth: 4,
        borderColor: "#fff",
        marginTop: -50,
        backgroundColor: "#fff",
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 6,
        overflow: "hidden",
    },
    avatarImg: { width: "100%", height: "100%", borderRadius: 50 },
    avatarFallback: {
        width: "100%",
        height: "100%",
        backgroundColor: "#e0e7ff",
        justifyContent: "center",
        alignItems: "center",
    },
    avatarInitial: { fontSize: 38, fontWeight: "800", color: NAVY },

    heroName: {
        fontSize: 22,
        fontWeight: "800",
        color: "#0f172a",
        marginTop: 14,
        paddingHorizontal: 24,
        textAlign: "center",
    },
    heroNickname: { fontSize: 14, color: "#64748b", marginTop: 2 },
    heroBio: {
        fontSize: 14,
        color: "#475569",
        textAlign: "center",
        marginTop: 10,
        lineHeight: 20,
        paddingHorizontal: 32,
    },

    socialStrip: {
        flexDirection: "row",
        gap: 14,
        marginTop: 18,
        justifyContent: "center",
    },
    socialIcon: { width: 30, height: 30, resizeMode: "contain", opacity: 0.85 },

    // ── Info Card ──
    infoCard: {
        backgroundColor: "#fff",
        marginHorizontal: 16,
        marginTop: 16,
        borderRadius: 16,
        paddingHorizontal: 20,
        paddingVertical: 18,
        gap: 14,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
    },
    infoCardTitle: {
        fontSize: 14,
        fontWeight: "700",
        color: "#64748b",
        textTransform: "uppercase",
        letterSpacing: 0.5,
        marginBottom: 2,
    },
    infoRow: { flexDirection: "row", alignItems: "center", gap: 14 },
    infoIconBox: {
        width: 38,
        height: 38,
        borderRadius: 10,
        justifyContent: "center",
        alignItems: "center",
    },
    infoTexts: { flex: 1 },
    infoLabel: {
        fontSize: 12,
        color: "#94a3b8",
        fontWeight: "500",
        marginBottom: 1,
    },
    infoValue: { fontSize: 15, color: "#1e293b", fontWeight: "600" },

    // ── Edit CTA ──
    editBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        backgroundColor: NAVY,
        marginHorizontal: 16,
        marginTop: 20,
        paddingVertical: 14,
        borderRadius: 14,
        elevation: 3,
        shadowColor: NAVY,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.25,
        shadowRadius: 8,
    },
    editBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },

    // ═══ EDIT MODAL ═══
    modalContainer: { flex: 1, backgroundColor: "#f1f5f9" },
    modalHeader: {
        backgroundColor: NAVY,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 12,
        paddingVertical: 14,
    },
    modalScroll: { padding: 16, gap: 4 },

    // Avatar section in modal
    modalAvatarSection: { alignItems: "center", marginBottom: 8 },
    modalAvatarWrap: {
        position: "relative",
        width: 90,
        height: 90,
        marginBottom: 8,
    },
    modalAvatarImg: { width: 90, height: 90, borderRadius: 45 },
    modalAvatarFallback: {
        width: 90,
        height: 90,
        borderRadius: 45,
        backgroundColor: "#e0e7ff",
        justifyContent: "center",
        alignItems: "center",
    },
    modalAvatarInitial: { fontSize: 32, fontWeight: "800", color: NAVY },
    modalCameraOverlay: {
        position: "absolute",
        bottom: 0,
        right: 0,
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: NAVY,
        justifyContent: "center",
        alignItems: "center",
        borderWidth: 2,
        borderColor: "#fff",
    },
    modalAvatarHint: { fontSize: 12, color: "#64748b" },
    modalUrlInput: {
        marginTop: 10,
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 8,
        fontSize: 13,
        color: "#334155",
        backgroundColor: "#fff",
        textAlign: "center",
        width: "100%",
    },
    historySection: {
        marginTop: 14,
        width: "100%",
        alignItems: "flex-start",
    },
    historyTitle: {
        fontSize: 12,
        fontWeight: "700",
        color: "#64748b",
        marginBottom: 6,
    },
    historyScroll: {
        gap: 8,
        paddingVertical: 4,
    },
    historyItemWrap: {
        width: 60,
        height: 60,
        borderRadius: 30,
        borderWidth: 2,
        borderColor: "transparent",
        padding: 2,
    },
    historyItemActive: {
        borderColor: "#3b82f6",
    },
    historyItemImg: {
        width: "100%",
        height: "100%",
        borderRadius: 26,
    },
    previewBackdrop: {
        flex: 1,
        backgroundColor: "rgba(0, 0, 0, 0.75)",
        justifyContent: "center",
        alignItems: "center",
    },
    previewContainer: {
        backgroundColor: "#1e293b",
        padding: 24,
        borderRadius: 20,
        width: "85%",
        alignItems: "center",
        position: "relative",
    },
    previewCloseBtn: {
        position: "absolute",
        top: 12,
        right: 12,
        padding: 4,
        zIndex: 10,
    },
    previewImage: {
        width: 220,
        height: 220,
        borderRadius: 110,
        borderWidth: 3,
        borderColor: "#fff",
        marginBottom: 24,
    },
    previewActions: {
        width: "100%",
        gap: 12,
    },
    previewActionBtn: {
        paddingVertical: 12,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
    },
    previewUseBtn: {
        backgroundColor: "#3b82f6",
    },
    previewDeleteBtn: {
        backgroundColor: "#ef4444",
    },
    previewActionTxt: {
        color: "#fff",
        fontSize: 14,
        fontWeight: "700",
    },

    groupLabel: {
        fontSize: 12,
        fontWeight: "700",
        color: "#94a3b8",
        textTransform: "uppercase",
        letterSpacing: 0.6,
        marginTop: 20,
        marginBottom: 8,
    },
    field: { marginBottom: 12 },
    fieldLabel: {
        fontSize: 13,
        fontWeight: "600",
        color: "#475569",
        marginBottom: 5,
    },
    fieldInput: {
        backgroundColor: "#fff",
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 10,
        fontSize: 15,
        color: "#0f172a",
    },
    fieldArea: { textAlignVertical: "top", minHeight: 72 },

    genderRow: { flexDirection: "row", gap: 10 },
    genderBtn: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        backgroundColor: "#fff",
        alignItems: "center",
    },
    genderBtnOn: { borderColor: NAVY, backgroundColor: "#eff6ff" },
    genderBtnTxt: { fontSize: 14, fontWeight: "600", color: "#64748b" },
    genderBtnTxtOn: { color: NAVY },

    rowPair: { flexDirection: "row", gap: 12 },

    socialField: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
        backgroundColor: "#fff",
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 2,
        marginBottom: 10,
    },
    socialFieldIcon: { width: 26, height: 26, resizeMode: "contain" },
    socialFieldInput: {
        flex: 1,
        fontSize: 15,
        color: "#0f172a",
        paddingVertical: 10,
    },

    // Days since joining badge
    daysBadge: {
        marginTop: 12,
        marginBottom: 4,
        backgroundColor: "#eff6ff",
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderWidth: 1,
        borderColor: "#bfdbfe",
    },
    daysBadgeText: {
        fontSize: 13,
        fontWeight: "700",
        color: NAVY,
    },

    // Date picker button
    datePickerBtn: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "#fff",
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 11,
    },
    datePickerTxt: {
        fontSize: 15,
        color: "#0f172a",
        flex: 1,
    },

    // Read-only join date
    readonlyField: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        backgroundColor: "#f8fafc",
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 11,
    },
    readonlyTxt: {
        fontSize: 15,
        color: "#64748b",
        flex: 1,
    },
    readonlyHint: {
        fontSize: 11,
        color: "#94a3b8",
        marginTop: 4,
        fontStyle: "italic",
    },
    streakCard: {
        backgroundColor: "#ffffff",
        borderRadius: 24,
        padding: 20,
        marginHorizontal: 16,
        marginTop: 16,
        borderWidth: 1.5,
        borderColor: "#ffedd5",
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
    },
    streakHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    streakTitle: {
        fontSize: 13,
        fontWeight: "800",
        color: "#ea580c",
        letterSpacing: 0.8,
    },
    streakStatusBadge: {
        backgroundColor: "#fff7ed",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#fed7aa",
    },
    streakStatusBadgeTxt: {
        fontSize: 10,
        fontWeight: "800",
        color: "#ea580c",
    },
    changeMascotHeaderBtn: {
        padding: 6,
        backgroundColor: "#ffffff",
        borderRadius: 24,
        borderWidth: 1.5,
        borderColor: "#fed7aa",
        justifyContent: "center",
        alignItems: "center",
        width: 46,
        height: 46,
        // Shadow properties for iOS
        shadowColor: "#ea580c",
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        // Elevation for Android
        elevation: 4,
    },
    changeMascotHeaderEmoji: {
        fontSize: 18,
    },
    streakMainContent: {
        alignItems: "center",
        justifyContent: "center",
    },
    streakBigImage: {
        width: 256,
        height: 256,
        maxWidth: "100%",
        resizeMode: "contain",
    },
    streakLevelNameTxt: {
        fontSize: 22,
        fontWeight: "800",
        color: "#ea580c",
        textAlign: "center",
        marginTop: 8,
    },
    streakLevelDescriptionTxt: {
        fontSize: 12,
        color: "#64748b",
        textAlign: "center",
        marginTop: 6,
        lineHeight: 18,
        paddingHorizontal: 16,
    },
    streakDaysTxt: {
        fontSize: 12,
        fontWeight: "700",
        color: NAVY,
        marginTop: 10,
        textAlign: "center",
    },
    progressBarWrapper: {
        marginTop: 16,
        position: "relative",
        height: 22, // đủ chỗ cho fire gif nổi lên trên
    },
    progressBarBg: {
        height: 10,
        backgroundColor: "#f1f5f9",
        borderRadius: 5,
        marginTop: 6,
        overflow: "hidden",
    },
    progressBarFill: {
        height: "100%",
        backgroundColor: "#ea580c",
        borderRadius: 5,
    },
    fireGif: {
        position: "absolute",
        top: -16,
        width: 22,
        height: 22,
        resizeMode: "contain",
    },
    streakRecoveryLimitTxt: {
        fontSize: 8,
        color: "#dddddd",
        fontWeight: "700",
        marginTop: 12,
        textAlign: "left",
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(15, 23, 42, 0.6)",
        justifyContent: "flex-end",
    },
    mascotModalContent: {
        backgroundColor: "#ffffff",
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        padding: 24,
        maxHeight: "80%",
    },
    mascotModalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    mascotModalTitle: {
        fontSize: 18,
        fontWeight: "800",
        color: "#0f172a",
    },
    mascotGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        paddingBottom: 20,
    },
    mascotCard: {
        width: "48%",
        backgroundColor: "#f8fafc",
        borderRadius: 16,
        padding: 16,
        alignItems: "center",
        marginBottom: 16,
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        position: "relative",
    },
    mascotCardActive: {
        borderColor: "#ea580c",
        backgroundColor: "#fff7ed",
    },
    mascotCardImage: {
        width: 80,
        height: 80,
        marginBottom: 12,
    },
    mascotCardName: {
        fontSize: 13,
        fontWeight: "700",
        color: "#475569",
        textAlign: "center",
    },
    mascotCardNameActive: {
        color: "#ea580c",
    },
    activeIndicatorBadge: {
        position: "absolute",
        top: 8,
        right: 8,
        backgroundColor: "#ea580c",
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 6,
    },
    activeIndicatorText: {
        color: "#ffffff",
        fontSize: 9,
        fontWeight: "800",
    },
});