import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
    },
    header: {
        backgroundColor: "#ffffff",
        padding: 24,
        paddingTop: 60,
        borderBottomWidth: 1,
        borderBottomColor: "#e2e8f0",
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#0f172a",
    },
    body: {
        padding: 24,
        gap: 6,
    },
    card: {
        backgroundColor: "#ffffff",
        padding: 12,
        borderRadius: 16,
        flexDirection: "row",
        alignItems: "center",
        gap: 16,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
    },
    iconContainer: {
        padding: 8,
        borderRadius: 12,
    },
    cardContent: {
        flex: 1,
    },
    cardTitle: {
        fontSize: 15,
        fontWeight: "600",
        color: "#1e293b",
        marginBottom: 4,
    },
    cardDesc: {
        fontSize: 14,
        color: "#64748b",
        lineHeight: 20,
    },
    // Modal styles
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(15, 23, 42, 0.6)",
        justifyContent: "flex-end",
    },
    modalContent: {
        backgroundColor: "#ffffff",
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingTop: 24,
        paddingHorizontal: 20,
        height: "75%",
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#0f172a",
    },
    modalTitleSub: {
        fontSize: 14,
        color: "#64748b",
    },
    modalTabs: {
        flexDirection: "row",
        backgroundColor: "#f1f5f9",
        borderRadius: 12,
        padding: 4,
        marginBottom: 20,
    },
    modalTab: {
        flex: 1,
        paddingVertical: 10,
        alignItems: "center",
        borderRadius: 8,
    },
    modalTabActiveExpense: {
        backgroundColor: "#ef4444",
    },
    modalTabActiveIncome: {
        backgroundColor: "#10b981",
    },
    modalTabText: {
        fontSize: 14,
        fontWeight: "600",
        color: "#64748b",
    },
    modalTabTextActive: {
        color: "#ffffff",
    },
    addCategoryRow: {
        flexDirection: "row",
        gap: 12,
        marginBottom: 20,
    },
    addCategoryInput: {
        flex: 1,
        borderWidth: 1,
        borderColor: "#cbd5e1",
        borderRadius: 12,
        paddingHorizontal: 16,
        paddingVertical: 12,
        fontSize: 16,
        backgroundColor: "#f8fafc",
    },
    addCategoryBtn: {
        backgroundColor: "#3b82f6",
        borderRadius: 12,
        width: 48,
        alignItems: "center",
        justifyContent: "center",
    },
    categoryListItem: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
    },
    categoryListName: {
        fontSize: 16,
        color: "#334155",
        fontWeight: "500",
    },
    footerInfo: {
        alignItems: "center",
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderTopWidth: 1,
        borderTopColor: "#f1f5f9",
        backgroundColor: "#ffffff",
    },
    versionRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        marginBottom: 4,
    },
    versionText: {
        fontSize: 14,
        color: "#64748b",
        fontWeight: "500",
    },
    versionSeparator: {
        marginHorizontal: 8,
        color: "#cbd5e1",
        fontSize: 14,
    },
    versionHistoryBtn: {
        fontSize: 14,
        color: "#3b82f6",
        fontWeight: "600",
        textDecorationLine: "underline",
    },
    authorText: {
        fontSize: 14,
        color: "#64748b",
    },
    authorHighlight: {
        fontWeight: "bold",
        color: "#3b82f6",
        fontStyle: "italic",
        fontSize: 15,
    },
    historyList: {
        marginTop: 8,
    },
    historyItem: {
        flexDirection: "row",
        marginBottom: 16,
    },
    historyDotContainer: {
        alignItems: "center",
        marginRight: 12,
        width: 16,
    },
    historyDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: "#3b82f6",
        marginTop: 6,
    },
    historyLine: {
        width: 2,
        flex: 1,
        backgroundColor: "#e2e8f0",
        marginTop: 4,
        marginBottom: -16,
    },
    historyContent: {
        flex: 1,
        backgroundColor: "#f8fafc",
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    historyVersion: {
        fontSize: 14,
        fontWeight: "bold",
        color: "#1e293b",
        marginBottom: 4,
    },
    historyDesc: {
        fontSize: 13,
        color: "#475569",
        lineHeight: 18,
        fontStyle: "italic",
        marginBottom: 8
    },
    // Setting styles
    settingSectionTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: "#64748b",
        marginBottom: 12,
        marginTop: 10,
        letterSpacing: 0.5,
    },
    settingGroup: {
        gap: 12,
    },
    settingOption: {
        backgroundColor: "#f8fafc",
        padding: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    settingOptionActive: {
        backgroundColor: "#eff6ff",
        borderColor: "#3b82f6",
    },
    settingOptionInfo: {
        flex: 1,
    },
    settingOptionTitle: {
        fontSize: 16,
        fontWeight: "700",
        color: "#0f172a", // Dark blue/black
        marginBottom: 4,
    },
    settingOptionTextActive: {
        color: "#2563eb", // Primary blue
    },
    settingOptionDesc: {
        fontSize: 13,
        color: "#475569", // Darker gray
        lineHeight: 18,
    },
    modalOverlayCenter: {
        flex: 1,
        backgroundColor: "rgba(15, 23, 42, 0.7)",
        justifyContent: "center",
        alignItems: "center",
        padding: 20,
    },
    settingsModalBox: {
        backgroundColor: "#ffffff",
        borderRadius: 24,
        padding: 24,
        width: "90%",
        maxWidth: 400,
        elevation: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.25,
        shadowRadius: 20,
    },
    settingItem: {
        marginBottom: 20,
    },
    closeSettingsBtn: {
        backgroundColor: "#f1f5f9",
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: "center",
        marginBottom: 46,
    },
    closeSettingsBtnText: {
        color: "#1e293b",
        fontSize: 16,
        fontWeight: "bold",
    },
    categoryIconContainer: {
        width: 38,
        height: 38,
        borderRadius: 8,
        backgroundColor: "#ecfdf5",
        justifyContent: "center",
        alignItems: "center",
    },
    categoryIcon: {
        width: 26,
        height: 26,
        resizeMode: "contain",
    },
    iconModalContent: {
        backgroundColor: "#ffffff",
        borderRadius: 24,
        padding: 24,
        width: "100%",
        maxHeight: "80%",
        elevation: 20,
    },
    iconModalSubtitle: {
        fontSize: 14,
        color: "#64748b",
        marginBottom: 16,
        lineHeight: 20,
    },
    iconGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "space-between",
        gap: 12,
        paddingVertical: 10,
    },
    iconGridItem: {
        width: "22%",
        aspectRatio: 1,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: "#e2e8f0",
        backgroundColor: "#f8fafc",
        justifyContent: "center",
        alignItems: "center",
        marginBottom: 4,
    },
    iconItemImage: {
        width: 38,
        height: 38,
        resizeMode: "contain",
    },
    driveStatusCard: {
        backgroundColor: "#f8fafc",
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        marginBottom: 20,
    },
    driveLoginBtn: {
        backgroundColor: "#0891b2",
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    driveLoginBtnText: {
        color: "#ffffff",
        fontSize: 15,
        fontWeight: "bold",
    },
    driveLogoutBtn: {
        backgroundColor: "#fee2e2",
        paddingVertical: 12,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: "#fecaca",
    },
    driveLogoutBtnText: {
        color: "#dc2626",
        fontSize: 15,
        fontWeight: "600",
    },
    driveOptionRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
        marginBottom: 16,
    },
    driveOptionTitle: {
        fontSize: 15,
        fontWeight: "600",
        color: "#1e293b",
        marginBottom: 4,
    },
    driveOptionDesc: {
        fontSize: 12,
        color: "#64748b",
        lineHeight: 16,
    },
    driveActionBox: {
        marginBottom: 20,
    },
    driveSectionTitle: {
        fontSize: 15,
        fontWeight: "600",
        color: "#1e293b",
        marginBottom: 6,
    },
    driveSectionDesc: {
        fontSize: 13,
        color: "#64748b",
        marginBottom: 12,
    },
    driveManualBtn: {
        backgroundColor: "#0891b2",
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    driveManualBtnText: {
        color: "#ffffff",
        fontSize: 15,
        fontWeight: "bold",
    },
    driveBtnDisabled: {
        backgroundColor: "#cbd5e1",
    },
    driveHistoryBox: {
        backgroundColor: "#f8fafc",
        borderRadius: 16,
        padding: 16,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    driveHistoryTitle: {
        fontSize: 14,
        fontWeight: "700",
        color: "#1e293b",
        marginBottom: 12,
    },
    driveHistoryRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 8,
    },
    driveHistoryLabel: {
        fontSize: 13,
        color: "#64748b",
    },
    driveHistoryValue: {
        fontSize: 13,
        color: "#1e293b",
    },
    driveWarningBox: {
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: "#e2e8f0",
    },
    driveWarningText: {
        fontSize: 11,
        color: "#94a3b8",
        lineHeight: 15,
    },
    driveRestoreBtn: {
        backgroundColor: "#16a34a",
        paddingVertical: 14,
        borderRadius: 12,
        alignItems: "center",
        justifyContent: "center",
    },
    driveRestoreBtnText: {
        color: "#ffffff",
        fontSize: 15,
        fontWeight: "bold",
    },
});