import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f8fafc",
    },
    header: {
        backgroundColor: "#ffffff",
        padding: 24,
        paddingTop: 60,
        borderBottomWidth: 1,
        borderBottomColor: "#e2e8f0",
    },
    headerRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#0f172a",
    },
    chartButton: {
        padding: 8,
        backgroundColor: "#eff6ff",
        borderRadius: 8,
    },
    barChartContainer: {
        backgroundColor: "#ffffff",
        borderRadius: 16,
        paddingVertical: 16,
        marginBottom: 16,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    chartTitle: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#334155",
        marginLeft: 16,
        marginBottom: 12,
    },
    pieModalOverlay: {
        flex: 1,
        backgroundColor: "#ffffff",
    },
    pieModalBox: {
        flex: 1,
        backgroundColor: "#ffffff",
        paddingBottom: 32,
        paddingTop: 40,
    },
    pieChartWrapper: {
        alignItems: "center",
        paddingVertical: 10,
        flex: 1, // Để danh sách chiếm hết phần còn lại
    },
    inlineNoteItem: {
        flexDirection: "row",
        justifyContent: "space-between",
        paddingVertical: 4,
    },
    inlineNoteText: {
        fontSize: 13,
        color: "#475569",
        flex: 1,
    },
    inlineNoteAmount: {
        fontSize: 13,
        fontWeight: "600",
        color: "#1e293b",
    },
    barChartHeader: {
        padding: 16,
        alignItems: "center",
    },
    barTooltipText: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#3b82f6",
    },
    barChartButtonContainer: {
        paddingHorizontal: 16,
        paddingTop: 8,
        paddingBottom: 16,
    },
    openBarChartBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#eff6ff",
        paddingVertical: 12,
        borderRadius: 12,
        gap: 8,
    },
    openBarChartBtnText: {
        color: "#3b82f6",
        fontWeight: "bold",
        fontSize: 16,
    },
    filterSection: {
        backgroundColor: "#ffffff",
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#e2e8f0",
    },
    periodFilters: {
        paddingHorizontal: 16,
        gap: 8,
    },
    periodBadge: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: "#f1f5f9",
    },
    periodBadgeActive: {
        backgroundColor: "#3b82f6",
    },
    periodText: {
        color: "#64748b",
        fontWeight: "600",
    },
    periodTextActive: {
        color: "#ffffff",
    },
    customDateContainer: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        marginTop: 12,
        gap: 8,
    },
    dateLabel: {
        color: "#64748b",
        fontWeight: "500",
    },
    dateBtn: {
        backgroundColor: "#f1f5f9",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    dateBtnText: {
        color: "#334155",
        fontWeight: "500",
    },
    typeTabs: {
        flexDirection: "row",
        marginTop: 16,
        paddingHorizontal: 16,
        gap: 8,
    },
    typeTab: {
        flex: 1,
        paddingVertical: 10,
        alignItems: "center",
        borderRadius: 8,
        backgroundColor: "#f1f5f9",
    },
    typeTabActive: { backgroundColor: "#3b82f6" },
    typeTabActiveExpense: { backgroundColor: "#ef4444" },
    typeTabActiveIncome: { backgroundColor: "#10b981" },
    typeTabText: {
        fontWeight: "600",
        color: "#64748b",
    },
    typeTabTextActive: {
        color: "#ffffff",
    },
    categoryFilters: {
        paddingHorizontal: 16,
        gap: 8,
        marginTop: 12,
    },
    categoryBadge: {
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#e2e8f0",
        backgroundColor: "#ffffff",
    },
    categoryBadgeActive: {
        backgroundColor: "#475569",
        borderColor: "#475569",
    },
    categoryText: {
        color: "#64748b",
        fontWeight: "500",
        fontSize: 13,
    },
    categoryTextActive: {
        color: "#ffffff",
    },
    listContent: {
        padding: 16,
        gap: 12,
        paddingBottom: 24,
    },
    card: {
        backgroundColor: "#ffffff",
        borderRadius: 12,
        padding: 16,
        elevation: 1,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
    cardRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 8,
    },
    cardCategory: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#1e293b",
    },
    cardName: {
        fontSize: 13,
        color: "#64748b",
        marginTop: 2,
        fontStyle: "italic",
    },
    cardAmount: {
        fontSize: 18,
        fontWeight: "bold",
    },
    expenseText: {
        color: "#ef4444",
    },
    incomeText: {
        color: "#10b981",
    },
    cardFooter: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    cardDate: {
        fontSize: 14,
        color: "#94a3b8",
    },
    actionRow: {
        flexDirection: "row",
        gap: 12,
    },
    actionButton: {
        padding: 4,
    },
    emptyContainer: {
        padding: 40,
        alignItems: "center",
    },
    emptyText: {
        color: "#94a3b8",
        fontSize: 16,
    },
    summaryContainer: {
        backgroundColor: "#ffffff",
        padding: 20,
        borderTopWidth: 1,
        borderTopColor: "#e2e8f0",
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
    },
    summaryRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 8,
    },
    summaryLabel: {
        fontSize: 15,
        color: "#64748b",
    },
    summaryLabelBold: {
        fontSize: 16,
        fontWeight: "bold",
        color: "#334155",
    },
    summaryIncome: {
        fontSize: 16,
        fontWeight: "600",
        color: "#10b981",
    },
    summaryExpense: {
        fontSize: 16,
        fontWeight: "600",
        color: "#ef4444",
    },
    summaryNetTop: {
        marginTop: 8,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: "#f1f5f9",
        marginBottom: 0,
    },
    summaryAmount: {
        fontSize: 18,
        fontWeight: "bold",
    },
    // Sub-filter danh mục đã xóa
    deletedSubFilter: {
        backgroundColor: "#fff7ed",
        borderTopWidth: 1,
        borderTopColor: "#fed7aa",
        paddingTop: 10,
        paddingBottom: 4,
    },
    deletedSubFilterLabel: {
        fontSize: 12,
        fontWeight: "600",
        color: "#c2410c",
        paddingHorizontal: 16,
        marginBottom: 6,
    },
    deletedCatBadge: {
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: "#fb923c",
        backgroundColor: "#fff7ed",
    },
    deletedCatBadgeActive: {
        backgroundColor: "#ea580c",
        borderColor: "#ea580c",
    },
    deletedCatText: {
        color: "#c2410c",
        fontWeight: "600",
        fontSize: 13,
    },
    deletedCatTextActive: {
        color: "#ffffff",
    },
    // Modal chọn tháng/năm
    modalOverlay: {
        flex: 1,
        backgroundColor: "rgba(0,0,0,0.45)",
        justifyContent: "center",
        alignItems: "center",
        padding: 24,
    },
    modalBox: {
        backgroundColor: "#ffffff",
        borderRadius: 16,
        width: "100%",
        maxHeight: 420,
        overflow: "hidden",
        elevation: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
    },
    modalTitle: {
        fontSize: 17,
        fontWeight: "bold",
        color: "#0f172a",
    },
    // Options Modal Styles
    optionsBox: {
        backgroundColor: "#ffffff",
        borderRadius: 20,
        width: "80%",
        padding: 20,
        alignItems: "center",
    },
    optionsTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#0f172a",
        marginBottom: 20,
    },
    optionBtn: {
        width: "100%",
        paddingVertical: 15,
        alignItems: "center",
    },
    optionTextEdit: {
        fontSize: 17,
        color: "#3b82f6",
        fontWeight: "600",
    },
    optionTextDelete: {
        fontSize: 17,
        color: "#ef4444",
        fontWeight: "600",
    },
    optionDivider: {
        height: 1,
        backgroundColor: "#f1f5f9",
        width: "100%",
    },
    optionCancelBtn: {
        marginTop: 10,
        width: "100%",
        paddingVertical: 15,
        alignItems: "center",
    },
    optionCancelText: {
        fontSize: 16,
        color: "#64748b",
        fontWeight: "500",
    },
    // Edit Modal Styles
    editModalOverlay: {
        flex: 1,
        backgroundColor: "rgba(15, 23, 42, 0.6)",
        justifyContent: "flex-start",
        paddingTop: 80,
        paddingHorizontal: 12,
    },
    editModalBox: {
        backgroundColor: "#ffffff",
        borderRadius: 24,
        paddingBottom: 24,
        width: "100%",
        elevation: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 12,
    },
    inputMethodToggleRow: {
        flexDirection: "row",
        paddingHorizontal: 16,
        marginBottom: 16,
        marginTop: 10,
    },
    quickToggleBtnCircle: {
        backgroundColor: "#ffffff",
        width: 34,
        height: 34,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
    },
    manualInputWrapper: {
        paddingHorizontal: 20,
        marginBottom: 20,
        marginTop: 10,
    },
    manualInput: {
        backgroundColor: "#f8fafc",
        borderWidth: 2,
        borderColor: "#e2e8f0",
        borderRadius: 16,
        padding: 20,
        fontSize: 24,
        fontWeight: "bold",
        color: "#0f172a",
        textAlign: "center",
    },
    editAmountDisplay: {
        paddingVertical: 30,
        alignItems: "center",
    },
    editAmountText: {
        fontSize: 40,
        fontWeight: "bold",
    },
    editConfirmBtn: {
        margin: 20,
        backgroundColor: "#7c3aed",
        paddingVertical: 16,
        borderRadius: 16,
        alignItems: "center",
    },
    editConfirmBtnText: {
        color: "#ffffff",
        fontSize: 18,
        fontWeight: "bold",
    },
    modalScroll: {
        maxHeight: 340,
    },
    modalItem: {
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#f8fafc",
    },
    modalItemActive: {
        backgroundColor: "#eff6ff",
    },
    modalItemText: {
        fontSize: 16,
        color: "#334155",
        fontWeight: "500",
    },
    modalItemTextActive: {
        color: "#3b82f6",
        fontWeight: "700",
    },
    modalEmpty: {
        textAlign: "center",
        color: "#94a3b8",
        fontSize: 15,
        paddingVertical: 32,
    },

    pieDetailTxCard: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#f1f5f9",
    },
    pieDetailTxLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        flex: 1,
    },
    pieDetailIconWrapper: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: "#fee2e2",
        justifyContent: "center",
        alignItems: "center",
    },
    pieDetailIcon: {
        width: 18,
        height: 18,
        resizeMode: "contain",
    },
    pieDetailName: {
        fontSize: 13,
        fontWeight: "600",
        color: "#1e293b",
    },
    pieDetailNote: {
        fontSize: 12,
        color: "#64748b",
        fontStyle: "italic",
        marginTop: 2,
    },
    pieDetailDate: {
        fontSize: 11,
        color: "#94a3b8",
        marginTop: 2,
    },
    pieDetailAmount: {
        fontSize: 13,
        fontWeight: "700",
        color: "#ef4444",
    },
    pieDetailLoadMoreBtn: {
        paddingVertical: 10,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: "#f8fafc",
        borderRadius: 10,
        marginTop: 8,
        borderWidth: 1,
        borderColor: "#e2e8f0",
    },
    pieDetailLoadMoreTxt: {
        fontSize: 13,
        fontWeight: "700",
        color: "#64748b",
    },
});
