import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f8fafc",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#ffffff",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "ios" ? 50 : 40,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  backButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#f1f5f9",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#0f172a",
    flex: 1,
    textAlign: "center",
    marginHorizontal: 8,
  },
  exportButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#ffe4e6",
  },
  yearScrollContainer: {
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
    paddingVertical: 12,
  },
  yearScrollContent: {
    paddingHorizontal: 16,
    gap: 12,
  },
  yearItem: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
    minWidth: 70,
    alignItems: "center",
    justifyContent: "center",
  },
  yearItemActive: {
    borderColor: "#f43f5e",
    backgroundColor: "#fff1f2",
  },
  yearText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#475569",
  },
  yearTextActive: {
    color: "#f43f5e",
    fontWeight: "bold",
  },
  content: {
    flex: 1,
  },
  contentContainer: {
    padding: 16,
    paddingBottom: 40,
  },
  pdfLikeBanner: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    elevation: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  appTitle: {
    fontSize: 11,
    fontWeight: "bold",
    color: "#94a3b8",
    letterSpacing: 1.5,
    textTransform: "uppercase",
    marginBottom: 6,
    textAlign: "center",
  },
  reportTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#0f172a",
    textAlign: "center",
    marginBottom: 6,
  },
  metaText: {
    fontSize: 12,
    color: "#64748b",
    fontStyle: "italic",
    textAlign: "center",
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1e293b",
    marginTop: 10,
    marginBottom: 14,
    borderLeftWidth: 4,
    borderLeftColor: "#f43f5e",
    paddingLeft: 10,
    letterSpacing: 0.5,
  },
  summaryGrid: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 20,
  },
  summaryCard: {
    flex: 1,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    padding: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  summaryLabel: {
    fontSize: 10,
    fontWeight: "bold",
    color: "#64748b",
    textTransform: "uppercase",
    marginBottom: 4,
    textAlign: "center",
  },
  summaryValue: {
    fontSize: 13,
    fontWeight: "bold",
    textAlign: "center",
  },
  valueIncome: {
    color: "#16a34a",
  },
  valueExpense: {
    color: "#dc2626",
  },
  tableCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 16,
    marginBottom: 20,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  tableTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 12,
  },
  tableHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    backgroundColor: "#f1f5f9",
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 6,
    marginBottom: 6,
  },
  tableHeaderText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#475569",
  },
  categoryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  categoryNameWrapperIncome: {
    backgroundColor: "#16a34a",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  categoryNameWrapperExpense: {
    backgroundColor: "#dc2626",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  categoryName: {
    fontSize: 12,
    color: "#ffffff",
    fontWeight: "bold",
  },
  categoryAmount: {
    fontSize: 13,
    fontWeight: "600",
  },
  detailsContainer: {
    backgroundColor: "#f8fafc",
    padding: 10,
    paddingLeft: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  detailsTitle: {
    fontSize: 10,
    fontWeight: "600",
    color: "#475569",
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  detailItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  detailBullet: {
    fontSize: 12,
    color: "#475569",
    marginRight: 4,
  },
  detailText: {
    fontSize: 12,
    color: "#475569",
    flex: 1,
  },
  detailAmount: {
    fontSize: 12,
    fontWeight: "600",
  },
  noDataText: {
    fontSize: 12,
    color: "#94a3b8",
    fontStyle: "italic",
    paddingVertical: 12,
    textAlign: "center",
  },
  monthSection: {
    marginTop: 20,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    padding: 16,
    marginBottom: 20,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
  monthTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#0f172a",
    borderBottomWidth: 2,
    borderBottomColor: "#fda4af",
    paddingBottom: 8,
    marginBottom: 14,
  },
  monthTableCard: {
    marginBottom: 12,
  },
  monthTableTitle: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 8,
  },
  pdfLoadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(255, 255, 255, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  pdfLoadingText: {
    marginTop: 12,
    color: "#e11d48",
    fontWeight: "600",
    fontSize: 14,
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 80,
  },
  emptyText: {
    fontSize: 15,
    color: "#64748b",
    textAlign: "center",
  },
});
